// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV4BXJMK5cQ18Aja7NlGuvR6Wi5ygaj6w',
    appId: '1:199948307038:web:3640ea34cb72547992c2cf',
    messagingSenderId: '199948307038',
    projectId: 'book-voyage-1ec98',
    authDomain: 'book-voyage-1ec98.firebaseapp.com',
    databaseURL: 'https://book-voyage-1ec98-default-rtdb.firebaseio.com',
    storageBucket: 'book-voyage-1ec98.firebasestorage.app',
    measurementId: 'G-48LY6PQ5M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jRjI5IwkLASsFtmzVemIVbapQsTAZZI',
    appId: '1:199948307038:android:d7759fd6c5833ed692c2cf',
    messagingSenderId: '199948307038',
    projectId: 'book-voyage-1ec98',
    databaseURL: 'https://book-voyage-1ec98-default-rtdb.firebaseio.com',
    storageBucket: 'book-voyage-1ec98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6-eWQkQ-jTxBfnyD-nnMgfygVPwmYT78',
    appId: '1:199948307038:ios:52b3a4681c9df84192c2cf',
    messagingSenderId: '199948307038',
    projectId: 'book-voyage-1ec98',
    databaseURL: 'https://book-voyage-1ec98-default-rtdb.firebaseio.com',
    storageBucket: 'book-voyage-1ec98.firebasestorage.app',
    iosBundleId: 'com.example.bookVoyageDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6-eWQkQ-jTxBfnyD-nnMgfygVPwmYT78',
    appId: '1:199948307038:ios:52b3a4681c9df84192c2cf',
    messagingSenderId: '199948307038',
    projectId: 'book-voyage-1ec98',
    databaseURL: 'https://book-voyage-1ec98-default-rtdb.firebaseio.com',
    storageBucket: 'book-voyage-1ec98.firebasestorage.app',
    iosBundleId: 'com.example.bookVoyageDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV4BXJMK5cQ18Aja7NlGuvR6Wi5ygaj6w',
    appId: '1:199948307038:web:4cc3b88715c4a03892c2cf',
    messagingSenderId: '199948307038',
    projectId: 'book-voyage-1ec98',
    authDomain: 'book-voyage-1ec98.firebaseapp.com',
    databaseURL: 'https://book-voyage-1ec98-default-rtdb.firebaseio.com',
    storageBucket: 'book-voyage-1ec98.firebasestorage.app',
    measurementId: 'G-NFSSXFP898',
  );
}
